name: 'Is this a release?'
description: "This action checks to see if the .version key in a repository's package.json has changed in order to determine if this commit is a release commit"

inputs:
  commit-starts-with:
    description: "Validate that the release commit starts with a string in this comma-separated list. Use '[version]' to refer to the current release version."
    required: false

  commit-message:
    description: "The commit message to check. If not provided, the action will get the message from the current commit."
    required: false
    default: ""

  before:
    description: "The commit SHA before the current commit."
    required: false
    default: ${{ github.event.before }}

  skip-checkout:
    description: "If 'true', the action will skip the checkout step. Use this if the repository has already been checked out. Note that the action requires at least two commits to be fetched."
    required: false
    default: "false"

outputs:
  IS_RELEASE:
    description: 'Is this a release? can be either "true" or "false".'
    value: ${{ steps.is-release.outputs.IS_RELEASE }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      if: ${{ inputs.skip-checkout != 'true' }}
      with:
        ref: ${{ github.sha }}
        # we need this commit + the last so we can compare below
        fetch-depth: 2
    - id: is-release
      shell: bash
      env:
        BEFORE: ${{ inputs.before }}
        COMMIT_STARTS_WITH: ${{ inputs.commit-starts-with }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
      run: ${{ github.action_path }}/scripts/is-release.sh
