name: 'Is this a release?'
description: "This action checks to see if the .version key in a repository's package.json has changed in order to determine if this commit is a release commit"

inputs:
  commit-starts-with:
    description: "Validate that the release commit starts with a string in this comma-separated list. Use '[version]' to refer to the current release version."
    required: false

  before:
    description: "The commit SHA before the current commit."
    required: false
    default: ${{ github.event.before }}

outputs:
  IS_RELEASE:
    description: 'Is this a release? can be either "true" or "false".'
    value: ${{ steps.is-release.outputs.IS_RELEASE }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}
        # we need this commit + the last so we can compare below
        fetch-depth: 2
    - id: is-release
      shell: bash
      run: ${{ github.action_path }}/scripts/is-release.sh "${{ inputs.before }}" "${{ inputs.commit-starts-with }}"
