name: Build, Lint, and Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          persist-credentials: false
          node-version: ${{ matrix.node-version }}
          cache-node-modules: true

  lint:
    name: Lint
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          persist-credentials: false
      - name: Validate RC changelog
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog --rc
      - name: Validate changelog
        if: ${{ !startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog
      - name: Lint shell scripts
        run: |
          shellcheck scripts/is-release.sh \
            .github/workflows/scripts/update-major-version-tag.sh
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
